In [1]:
import pandas as pd
import numpy as np

In [2]:
df_bowl=pd.read_csv("/home/g1/Desktop/IPL/Bowling data/bowl.csv")
df_bat=pd.read_csv("/home/g1/Desktop/IPL/Batting data/bat.csv")

In [18]:
df_bowl=df_bowl.drop(columns="0")

In [19]:
df_bowl.head()

1          2          3          4          5          6  \
0  70.166667   0.000000  85.250000  24.101667  37.450000   0.000000   
1  27.080000  24.346667   0.000000  20.976667  23.146667  20.711667   
2  24.000000  24.193333  18.440000  27.360000   0.000000  21.106667   
3   0.000000  23.616667  21.906667  35.466667   0.000000  20.066667   
4   0.000000   0.000000  22.413333  25.906667  24.581667  23.463333   

           7          8          9         10  ...      57     58      59  \
0  22.920000  15.941667  21.673333  22.888333  ...  0.0000  6.930  7.2075   
1   0.000000  20.766667  27.468333  26.026667  ...  9.4950  7.240  7.5600   
2  23.413333  20.166667  23.356667  18.483333  ...  8.1525  7.605  7.7850   
3  17.943333  23.430000  13.686667  22.145000  ...  7.9350  6.840  7.1550   
4  18.413333  22.885000  16.695000  18.860000  ...  7.3200  7.065  8.0900   

       60      61     62      63      64      65      66  
0  6.4400  6.6750  0.000  7.7500  7.9350  6.6675  8.2900  
1  7.5525  7.6250  7.920  8.1150  6.8700  7.0800  6.0425  
2  6.7200  7.1100  6.420  0.0000  6.3750  7.3500  7.7575  
3  8.6925  0.0000  6.645  7.2725  7.4825  6.1650  7.5950  
4  8.8100  6.8275  9.360  7.4550  6.0250  7.2525  6.6725  

[5 rows x 66 columns]

In [4]:
p=np.arange(66)
pba=p[:22]
pbs=p[22:44]
pbe=p[44:66]

In [5]:
pba=pba.reshape([2,11])

In [6]:
pbs=pbs.reshape([2,11])

In [7]:
pbe=pbe.reshape([2,11])

In [8]:
pba.shape

(2, 11)

In [9]:

x=np.hstack(pba)
y=np.hstack(pbs)
z=np.hstack(pbe)
xyz=[np.hstack([x,y,z])]
xyz

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])]

In [20]:
t=df_bowl.values[0]

In [21]:
p=t
pba=p[:22]
pbs=p[22:44]
pbe=p[44:66]
pba=pba.reshape([2,11])
pbs=pbs.reshape([2,11])
pbe=pbe.reshape([2,11])


In [22]:
pba

array([[70.16666667,  0.        , 85.25      , 24.10166667, 37.45      ,
         0.        , 22.92      , 15.94166667, 21.67333333, 22.88833333,
        19.42      ],
       [25.90666667,  0.        , 22.41333333, 24.58166667, 23.46333333,
        18.41333333,  0.        , 22.885     , 16.695     , 18.86      ,
        34.65      ]])

In [23]:
pbs

array([[79.46666667,  0.        , 76.98333333, 24.46666667, 34.23333333,
         0.        , 31.        , 19.86666667, 21.85      , 22.25      ,
        28.33333333],
       [31.93333333,  0.        , 29.06666667, 25.7       , 27.56666667,
        24.8       ,  0.        , 21.06666667, 16.31666667, 25.73333333,
        28.25      ]])

In [24]:
pbe

array([[7.935 , 0.    , 8.6925, 7.155 , 7.69  , 0.    , 6.645 , 6.135 ,
        7.2725, 7.4825, 6.165 ],
       [7.29  , 0.    , 6.93  , 7.2075, 6.44  , 6.675 , 0.    , 7.75  ,
        7.935 , 6.6675, 8.29  ]])